[package]
name = "echoro-backend"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "entity", "migration"]

[dependencies]
actix-web = "4"
async-std = "1.13.1"
dotenv = "0.15.0"
entity = { version = "0.1.0", path = "entity" }
sea-orm = { version = "1.1.12", features = ["sqlx-postgres", "runtime-async-std-native-tls", "macros"] }
sea-orm-migration = { version = "1.1.12", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
